name: Environment Variables
on:
  workflow_dispatch:
env:
  WORKFLOW_VAR: I_AM_WORKFLOW_SCOPED

jobs:
  job-1:
    runs-on: ubuntu-24.04
    env:
      JOB_VAR: I_AM_JOB_1_SCOPED
    steps:
      - name: Inspect scopes job 1 step 1
        env:
          STEP_VAR: I_AM_STEP_SCOPED
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"   # 可见
          echo "JOB_VAR:      $JOB_VAR"        # 可见
          echo "STEP_VAR:     $STEP_VAR"       # 仅在此处可见

      - name: Inspect scopes job 1 step 2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"         # 可见
          echo "JOB_VAR:      $JOB_VAR"              # 可见
          echo "STEP_VAR:     ${STEP_VAR:-<UNSET>}"  # 此处未设置

  job-2:
    runs-on: ubuntu-24.04
    steps:
      - name: Inspect scopes job 2 step 2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"                 # 仍然可见
          echo "JOB_VAR:      ${FOO:-<UNSET>}"               # 此处未设置
          echo "STEP_VAR:     ${STEP_VAR:-<UNSET>}"          # 此处未设置
